server.port=${PORT:8080}
spring.application.name=api-gateway
jwt.secret=${JWT_SECRET}

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=usuario-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${USUARIO_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/usuarios/**

spring.cloud.gateway.server.webmvc.routes[2].id=membresia-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${MEMBRESIA_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/membresias/**

# redeploy
